name: Sol
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17214
title: Sol alarm clock
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#505050'
    - '#c0c0c0'
    - '#272727'
  brandStrength: 0.9874205533415079
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
